openapi: 3.0.0
info:
  title: Items API
  description: API for managing items
  version: 1.0.0
paths:
  /items:
    get:
      summary: Retrieve a list of items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      summary: Retrieve a single item by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the item to retrieve
          schema:
            type: string
      responses:
        '200':
          description: An item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
    put:
      summary: Update an existing item
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the item to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Item updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
    delete:
      summary: Delete an item
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the item to delete
          schema:
            type: string
      responses:
        '204':
          description: Item deleted
        '404':
          description: Item not found
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "Sample Item"
        description:
          type: string
          example: "This is a sample item."
        price:
          type: number
          format: float
          example: 19.99
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"